Update datasets
cp3-llbb/Datasets pull request #35
Opened 2016-11-09 10:50 UTC by blinkseb

- Include Run2016H datasets
  - Update JSON file to the latest one
  - Use rereco for 2016B-G
  - Add new TT sample with new tune (unfortunately less statistics than the old sample and no fully leptonic sample)
  - Remove inexistent TT sample
  - Update HH analysis to include also inclusive TT samples

2016-11-09 12:38 UTC, blinkseb commented
Updated DY NLO sample

2016-11-09 13:34 UTC, blinkseb commented
Global tags added for data samples

2016-11-10 08:41 UTC, blinkseb commented
It seems like `Run2016H-PromptReco-v1` contains no certified runs. I'll remove it from the list

2016-11-10 09:05 UTC, BrieucF commented
Is it annoying to leave it there for the moment? There are still JSON updates foreseen and they sometimes recover runs.

2016-11-10 09:14 UTC, blinkseb commented
crab complains there's no job for this task and leave an empty folder, but otherwise no issue.

2016-11-11 19:37 UTC, OlivierBondu requested changes
Thanks ! looking good except two small corrections !

2016-11-11 19:37 UTC, OlivierBondu commented on datasets/data_DoubleEG.json
>              "run_range": [278820, 999999],
could you update the end run for Run2016G ?

2016-11-11 19:37 UTC, OlivierBondu commented on datasets/data_MuonEG.json
>              "run_range": [278820, 999999],
same here

2016-11-14 16:48 UTC, blinkseb commented
End run for 2016G updated. I also added a new commit updating HT binned DY samples

2016-11-15 08:19 UTC, OlivierBondu approved these changes

2016-11-15 08:20 UTC, OlivierBondu commented
thanks!

2016-11-15 08:20 UTC, merged